version: '2.1'
services:
  bar-archive-message-broker:
    image: rabbitmq:3-management
    container_name: bar-archive-rabbit-mq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - bar-archive-net
    ports:
      - '5672:5672'
      - '15672:15672'
    hostname: bar-archive-message-broker
    depends_on:
      - psql-bar-archive-service-db
  psql-bar-archive-service-db:
    image: postgres
    container_name: psql-bar-archive-service
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: barArchiveDB
    ports:
        - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - psql-bar-archive-service-data:/var/lib/postgresql/data
    networks:
      - bar-archive-net
  psql-bar-archive-auth-service-db:
    image: postgres
    container_name: psql-bar-archive-auth-service
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: keycloak
    ports:
        - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - psql-bar-archive-auth-service-data:/var/lib/postgresql/data
    networks:
      - bar-archive-net
  bar-archive-auth-service:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: bar-archive-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://psql-bar-archive-auth-service-db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: example
      KC_HOSTNAME: localhost
    ports:
      - '8080:8080'
    depends_on:
      psql-bar-archive-auth-service-db:
        condition: service_healthy
    command:
      ["start-dev"]
    networks:
      - bar-archive-net
  bar-archive-protobufs:
    image: bar-archive-dynamic-protos
    build: ./bar-archive-protos
  bar-archive-service-backend:
    image: bar-archive-service-backend
    container_name: bar-archive-service
    restart: always
    build: ./bar-archive-service
    ports:
      - '50051:50051'
    depends_on:
      psql-bar-archive-service-db:
        condition: service_healthy
    networks:
      - bar-archive-net
  bar-archive-api-gateway:
    image: bar-archive-api
    container_name: bar-archive-api-gateway
    restart: always
    build: ./bar-archive-api-gateway
    ports:
      - '8000:8000'
    depends_on:
      - bar-archive-service-backend
      - bar-archive-auth-service
    networks:
      - bar-archive-net
  bar-archive-email-service-backend:
    image: bar-archive-email-service-backend
    container_name: bar-archive-email-service
    restart: always
    build: ./bar-archive-email-service
    depends_on:
      - bar-archive-message-broker
    networks:
      - bar-archive-net

networks:
  bar-archive-net:

volumes:
  psql-bar-archive-service-data:
  psql-bar-archive-auth-service-data:
